language: java
jdk: openjdk11
os: linux
dist: xenial
cache:
  timeout: 180
  directories:
  - "$HOME/.m2/repository"
install:
- mvn install -U -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- if [[ "$TRAVIS_BRANCH" =~ master* ]]; then mvn test -B -P release; fi
- if ! [[ "$TRAVIS_BRANCH" =~ master* ]]; then mvn test -B; fi
before_deploy:
- if [[ "$TRAVIS_BRANCH" =~ master* ]]; then echo $GPG_SECRET_KEYS | base64 --decode
  | $GPG_EXECUTABLE --import; fi
- if [[ "$TRAVIS_BRANCH" =~ master* ]]; then echo $GPG_OWNERTRUST | base64 --decode
  | $GPG_EXECUTABLE --import-ownertrust; fi
deploy:
- provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests=true
  cleanup: false
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P release
    -DskipTests=true
  cleanup: false
  skip_cleanup: true
  on:
    branch: master
before_cache:
- rm -rf $HOME/.m2/repository/info/cqframework/cql.ls
notifications:
  slack:
    rooms:
      secure: JSgd6GecVhFMJSRR1pTpgiUTOhIhRutirH+olwTJM+jndClFnKJ7LKlCiU9s9t+BdKxdj3lmd2FmLYa+7Lh/XoP/D/jtOPqiNl6JZAeJs6cfROrZ5DO6Jt+oTYXEAqNGfqMQERy+peraWvSBQsHocWxGttF6nuUrwPAiMy7aWCkrWxB0tMV0+k0u49esnjD1osgiCaCE0biMOuVIs2k3vmTM4W9W2tUP2HHSz8djQLco3JMxy2ssgIppXuKSE9OGLt/WyThz6bjDBD4Vgiw98FxC26ipGp3s3Cr3M/Ogong69170dyi1ap9ALJX7aZqjqPlVV+FsCndt3MFuxakngLaR1X29PC6XIFetTbXHXHs1C2RJe21nrzf0VCvgusXF0eBjkTy4U8fRw3ZYPfgSJrJ43URHp2llygiBvGa6AIxRw0lIMne9hwDpqX+fGmhB/Ltr+xAEmeKkXM5zSAQj/oYVtYdQ+MvS+bAe4AqlqjfSrjyb4Cs+z5AQ/QUqJPRBQwsyZI/kcP64odHsCc3P7FkkOSIS6FKN2h0tEtBNyzDA1RCCoOw8dbB1KFzc4lj6Y8CU9iQtTGCmdb0YO2O1/qEWW7p0Gl9/B/FMMY4W6nFewlaB4HlR0UTtNBa0iCcA1wUJKWQjQqwoQGJV0ZbNhwb5uaMUFlUYIAVk1GqLqFo=
