language: java
jdk: openjdk11
os: linux
dist: xenial
cache:
  timeout: 180
  directories:
  - "$HOME/.m2/repository"
install:
- ./scripts/install.sh
script:
- ./scripts/test.sh
before_cache:
- rm -rf $HOME/.m2/repository/org/opencds/cqf/cql
after_success:
- ./scripts/deploy.sh
deploy:
  provider: releases
  api_key:
    secure: O6kK3bjPokEmIbigP+smS/ORYthxU5VxLLBxkx9yHJ9fooHolsFhlG/Qvr22KsfaXvvxgMV4f5VAj5X4zHxX6YZhGN/o+dWCfAGpuSUwohgxIKBfJl7Vwj/R29auxnSqRQvs6mokuMcXH+RbbddLydaqsVcClNc7DKRPFiGwCJly29zoSS73pYA5JAQXxS2dG+uwjeDS4iNlrQikJE7zXwqH48wLcwhcHqE2lWELYauMAAzWNPuP/et2ZbsMH04VEke4CR/nH0gc8tZmOJ5M1nlnyEWl40OGt+fuRmiDWcM2q1nlcsRPO1aRwSNOMTelUGlnCeBJ6eP1v4mur+L2r+G4GPZrbs6bjlcZc6UgHzLPiwR5wUUekmKUP3CfZJQijjlILLPfyTDEMYtx7NW+Odo2tqkt+MINp0d+aavMjeeNkh6UQSBuX2L5O1NIwI87tNTLGhd9NIaRgfTULBO3fWjWA6tgUXHtplgLkRhist6Zh26vjf0tCTzgPS5CMxtjwUPRl03LVNNyDYvnNQ1XTcYAAkmH/841oNmQovC/wqNrNzDiKNDdrAubrRtGZI4P91WRhEjaJOSK7TVwpWq3JqLisMimQarCyalTUZzPBudwWsjb6gZBKs3qzrRpGtR8QXASV73Cok0W4fPKgL5Hg4/HWINMkjfOICMNCSK6fHc=
  file_glob: true
  file: "target/*.jar"
  skip_cleanup: true
  name: CQL Language Server $TRAVIS_TAG
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true
notifications:
  slack:
    - rooms:
      - secure: E2fiQ2RaWa3em8jZtuYlwtGgBSzIvYdq1eSxffzeHErbvbwiO2gQ9Bs5FXCXguQFKtz6vAxgKHTs8ODRStf70rRmtf4asd8N8jmWuaQBQgpbinlM3lVns5GMgdwwOqjDgDM9BVYtsh/rIUOgT5mXI4yTVdKUh451l6daqCwnwbYnHAMqJWsctFEH2bqQvIAWrabsLSDKp46xVDL32pZ3C4LOCRQpH69w8N3qG9eilucsKl5rCtyuN6+J4eMCa5k/rq0kYMX3kV3dQ+9a+NozU1wqOcRHL7pUmCJQGXB6oUpOeciKkYdkDgUupnrzwaTQ4U3cLruME8SMa5EFlLy0zolbyV4oYWsxNRuTXTuEOE67ZNM/D0Dp7Kno6KK90/zSlrLlrbk51iEQU1/AZPVieYQtsTFT1ZgH8gKsieZE28v10JLM9yY4cS4bUvT390/yvNVV4LNjANozP6nZpvjzKg0D5dAGd33mtrug50ho0qxfiVzkSGyErvc2OWkRBBIFpKQv0hCfHIk5WPDkuAo3OyHKqx0S19uNaP7qnQaIuOJXXlNYAPzALIQKBIMH1suVnw36e3/3lZFIeJcl+4FLiyWnFJ0rm4eDsEtSQz7xL5wZ74zYMiOmIZwVpkzxtBt7YhGtpELbp0CYQ6fp7+fP8IyO+0vtnDBcqamLYhdISpw=
      on_success: always
      on_failure: never
    - rooms:
      - secure: WlqdWFfxZHsD0WjDEgK+pVzWr92t2RiAsq6XHSLJwHRCKcXMjdPOjbNK+LtbAc94Xz6jNj1uZF6BMwHnJ6ZNtSW9nlfzBZv4zz6iXxV5k1ysn6lHHlYeMNrDhar3LFvEAMlN5/65akiFuNQVMmIf5dTaiEk5Fkc00Pkcf74UBZpO6PTMBGUjObn1Cd4E0FLUGpA+2PDOwodMG6Oi7/ChEGU2JLKPutMTx1CwdCJJtFMAShsxIGRpDb5X1J9aJq+YVbGqTe+juuQh7eZA7We9+iT7dacri/obNpOUJ1KT1pufYtZtdetuFWz0dzAsoFjOCJPJicR7l8TyVvKk7C/EftzZ/mpS01X79NpqBl0YgErvjF+aRTjIlj0s4VBz1K8X7+K46Ueb/q7+RJ/s/xU1SBbRhkFQsXMIJPgV2ttNfUNdH2LRnnn4OyQu/0FApGy6UvHmgoO3p0lHlbSoD7viEtf1LTmVYaNcqEkC8e0OQlOtCLX7Diyk8tBMqm6yFVbw8TNF3JzDvyhsfdnQsP2Sd44GBYa38M4Xoyr0TvJd3JaGTJ67VgdUef03E9InJmAgRHQ1kCZ+helxUnL4b5Pq9cspDvRxN7lpXOojr990TJCKXbP52nigRqT5Lt13CDtbx4v253cwpZ3UjI6mvrgvRgNAf+X6Kxop2bcSUUG/ubY=
      on_success: never
      on_failure: always

